#!/bin/sh

. /etc/profile

#sudo=""; [ "$(stat -f %u "$0")" -eq 0 ] || sudo=/usr/bin/sudo

# For the link to be owned by sudo: sudo ln -s ./user ./root
env | grep -E "PROPERTIES|VM_OPTIONS" | awk -F '=' '{ print $1 }' | while read -r variable; do
  [ "${variable-}" ] || continue
  value="$(eval echo \$"${variable}")"
  launchctl setenv "${variable}" "${value}"
done
